"""
test_pipeline
DAG auto-generated by Astro Cloud IDE.
"""

from airflow.decorators import dag
from astro import sql as aql
from include.extensions.operators.custom_snowflake_operator_async import SnowflakeAuditLogOperator
import pandas as pd
import pendulum

# from include.functions.example_functions import print_sucess


@aql.dataframe(task_id="python_1")
def python_1_func():
    # print_sucess()

@dag(
    schedule="0 0 * * *",
    start_date=pendulum.from_format("2023-07-11", "YYYY-MM-DD").in_tz("UTC"),
    catchup=False,
)
def test_pipeline():
    python_1 = python_1_func()

    call__e_d_w__snowflake__custom__operator_1 = SnowflakeAuditLogOperator(
        task_id="call__e_d_w__snowflake__custom__operator_1",
    )

dag_obj = test_pipeline()
